# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('OS', 'One-shot Page'), ('SP', 'Series Page')], default='OS', max_length=2)),
                ('is_public', models.BooleanField(db_index=True)),
                ('public_publish_date', models.DateField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('last_modified_by', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(null=True, upload_to=pages.utils.feature_img_url)),
                ('uploaded_files', models.FileField(upload_to=pages.utils.upload_file_url)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('associated_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='current_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.Release'),
        ),
        migrations.AddField(
            model_name='page',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.Series'),
        ),
    ]
