# Generated by Django 2.0.5 on 2018-05-23 02:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20180519_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='packages.Package'),
            preserve_default=False,
        ),
    ]
