# Generated by Django 2.0.2 on 2018-10-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20180523_0211'),
        ('packages', '0005_auto_20180530_0148'),
    ]

    operations = [
    ]
