# Generated by Django 2.1 on 2018-10-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_merge_20181003_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='_content_type',
            field=models.CharField(blank=True, choices=[('PT', 'Plaintext'), ('HL', 'HTML')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='packageset',
            name='default_content_type',
            field=models.CharField(choices=[('PT', 'Plaintext'), ('HL', 'HTML')], default='PT', max_length=2),
        ),
    ]
