# Generated by Django 2.1 on 2018-10-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_merge_20181003_0252'),
        ('packages', '0007_auto_20181012_0142'),
    ]

    operations = [
    ]
