# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_current_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='current_release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.Release'),
        ),
    ]
