# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_current_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='current_release',
        ),
    ]
