# Generated by Django 2.0.2 on 2018-02-28 18:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('processing', models.BooleanField(default=False)),
                ('cached_article_preview', models.TextField()),
                ('publish_date', models.DateField()),
                ('last_fetched_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
