# Generated by Django 2.0.2 on 2018-03-02 20:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('processing', models.BooleanField(default=False)),
                ('cached_article_preview', models.TextField()),
                ('publish_date', models.DateField()),
                ('last_fetched_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageSet',
            fields=[
                ('slug', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='package_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.PackageSet'),
        ),
    ]
