# Generated by Django 2.0.2 on 2018-05-17 01:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('packages', '0001_initial'), ('packages', '0002_auto_20180304_0020'), ('packages', '0003_package_data'), ('packages', '0004_auto_20180509_0218'), ('packages', '0005_auto_20180509_0608'), ('packages', '0006_auto_20180516_0325'), ('packages', '0007_auto_20180516_0328'), ('packages', '0008_packageversion_version_description'), ('packages', '0009_auto_20180517_0135')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('processing', models.BooleanField(default=False)),
                ('cached_article_preview', models.TextField()),
                ('publish_date', models.DateField()),
                ('last_fetched_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageSet',
            fields=[
                ('slug', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('drive_folder_id', models.CharField(blank=True, max_length=512)),
                ('drive_folder_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='package_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.PackageSet'),
        ),
        migrations.AlterField(
            model_name='package',
            name='cached_article_preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_data', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='version_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='creator',
            field=models.TextField(blank=True),
        ),
    ]
