# Generated by Django 2.0.2 on 2018-02-25 01:21

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('drive_folder_id', models.CharField(max_length=512)),
                ('drive_folder_url', models.URLField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
                ('cached_article_preview', models.TextField()),
                ('publish_date', models.DateField()),
                ('last_fetched_date', models.DateField(null=True)),
            ],
        ),
    ]
