# Generated by Django 2.0.2 on 2018-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
