# Generated by Django 2.0.2 on 2018-03-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cached_article_preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packageset',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
