# Generated by Django 2.0.2 on 2018-03-01 02:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20180228_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='images',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
