# Generated by Django 2.0.2 on 2018-05-17 02:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('packages', '0004_auto_20180509_0218'), ('packages', '0005_auto_20180509_0608'), ('packages', '0006_auto_20180516_0325'), ('packages', '0007_auto_20180516_0328'), ('packages', '0008_packageversion_version_description')]

    dependencies = [
        ('packages', '0003_package_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_data', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='version_description',
            field=models.TextField(blank=True),
        ),
    ]
