# Generated by Django 2.0.2 on 2018-03-02 02:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20180301_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
