# Generated by Django 2.0.2 on 2018-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20180509_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageversion',
            name='package',
        ),
        migrations.AddField(
            model_name='packageversion',
            name='slug',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
