# Generated by Django 2.0.2 on 2018-05-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20180509_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageversion',
            name='slug',
        ),
        migrations.AddField(
            model_name='packageversion',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package'),
        ),
    ]
