# Generated by Django 2.0.2 on 2018-05-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20180516_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='version_description',
            field=models.TextField(blank=True),
        ),
    ]
