# Generated by Django 2.0.2 on 2018-05-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_packageversion_version_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='creator',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package'),
        ),
    ]
