# Generated by Django 2.0.2 on 2018-05-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20180517_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package'),
        ),
    ]
