# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(null=True, upload_to='profile/imgs/')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('role', models.CharField(choices=[('CT', 'Contributor'), ('PM', 'Project Manager'), ('ST', 'Senior Staff'), ('AE', 'Assistant Editor'), ('ED', 'Editor')], default='CT', max_length=2)),
            ],
            options={
                'default_related_name': 'profile',
            },
        ),
    ]
